service: lambda-test

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1



functions:
  app:
   handler: GetCustomerHandler.Productnm
   events:
   
    - alexaSkill:
       



          

plugins:
  - serverless-offline


  # app:
  #   handler: app.server # reference the file and exported method
  #   events: # events trigger lambda functions
  #     - http: # this is an API Gateway HTTP event trigger
  #         path: /
  #         method: get
  #         cors: true
  #     - http: # all routes get proxied to the Express router
  #         path: /{proxy+}
  #         method: ANY
  #         cors: true

  #############
